apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-stack  
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SystemConsultantGroup/SCG-Monitoring-Config.git'
    path: charts/kube-prometheus-stack
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            alertmanager:
              config:
                global:
                  slack_api_url: <path:kv/data/slack-secret#url>
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
