apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-stack  
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
    plugin:
      env:
        - name: HELM_VALUES 
          value: |
            alertmanager:
              config:
                global:
                  slack_api_url: <path:kv/data/slack-secret#url> 
    helm:
      valueFiles:
      - $values/charts/prometheus-operator/values/value.yaml
  - repoURL: 'https://github.com/SystemConsultantGroup/SCG-Monitoring-Config.git'
    targetRevision: main
    ref: values
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
